name: Deploy with Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          # Use a specific version for stability, check for the latest
          version: 1.70 

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server via Tailscale
        run: |
          # Use the Tailscale MagicDNS name of your server. No IP needed!
          # The command will only succeed because of the ACL rule you created.
          ssh -o StrictHostKeyChecking=accept-new your-user@deployment-server "echo 'Deployment successful via Tailscale!'"
