name: Deploy with Tailscale OAuth

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Required for the Tailscale OIDC authentication flow
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          # Use the new OAuth parameters
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          # The tag is now applied by the OAuth client, not here
          tags: ci-runner

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server via Tailscale
        run: |
          # The rest of your script remains the same
          ssh -o StrictHostKeyChecking=accept-new root@java-web2 "echo 'Deployment successful via Tailscale!'"
