name: Build and Deploy to Tailscale Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven Wrapper
        working-directory: demo # Run commands inside the 'demo' folder
        run: |
          chmod +x ./mvnw
          ./mvnw -B package --file pom.xml -DskipTests

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci-runner 

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Diagnose SSH Connection and Environment
        run: |
          # This is a temporary script for debugging
          ssh -o StrictHostKeyChecking=accept-new root@java-web2 '
            echo "✅ --- Connection successful ---"
            
            echo "WHOAMI: $(whoami)"
            echo "HOSTNAME: $(hostname)"
            
            echo "--- Checking for required commands ---"
            echo "PATH: $PATH"
            echo "pkill location: $(command -v pkill)"
            echo "java location: $(command -v java)"
            
            echo "--- Checking permissions for /opt/apps ---"
            ls -ld /opt/apps
            
            echo "✅ --- Diagnostic script finished successfully ---"
          '
